# 1. FLOW IDENTITY
# Every flow needs a unique ID and a Namespace.
# In a real company, namespace would be 'com.company.marketing' or 'com.company.finance'.
id: 01_hello_world
namespace: zoomcamp

# 2. INPUTS (The Arguments)
# These are dynamic values you pass when you click "Execute".
# SENIOR TIP: Always define 'defaults' so you can test quickly without typing every time.
inputs:
  - id: name
    type: STRING
    defaults: Will

# 3. CONCURRENCY (The Traffic Control)
# This prevents too many versions of this flow from running at once.
# If you click "Execute" 3 times fast, the 3rd one will FAIL immediately.
# REAL WORLD: Used to prevent crashing your database with 50 simultaneous big queries.
concurrency:
  behavior: FAIL
  limit: 2

# 4. VARIABLES (The Reusable Logic)
# These are calculated ONCE at the start.
# Note the syntax: {{ inputs.name }} grabs the value from the input section above.
variables:
  welcome_message: "Hello, {{ inputs.name }}!"

# 5. TASKS (The Steps)
# This is the sequence of work. Kestra runs them one by one.
tasks:
  # Task 1: Print the variable we defined above.
  # "render()" is a function to process the variable string.
  - id: hello_message
    type: io.kestra.plugin.core.log.Log
    message: "{{ render(vars.welcome_message) }}"

  # Task 2: Create some Data (Output).
  # This task doesn't just do work; it produces a result we need later.
  # The 'Return' task is just for debugging/learning outputs.
  - id: generate_output
    type: io.kestra.plugin.core.debug.Return
    format: I was generated during this workflow.

  # Task 3: Simulate a long job.
  # 'PT15S' is ISO 8601 format for "Period Time 15 Seconds".
  # We use this here to keep the flow running long enough to test the Concurrency limit.
  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT15S

  # Task 4: CONSUME THE OUTPUT (Critical Concept)
  # Watch the syntax: {{ outputs.task_id.value }}
  # This grabs the result from Task 2 ("generate_output") and uses it here.
  # In the real world, this would be: "Get the filename downloaded by Task 2".
  - id: log_output
    type: io.kestra.plugin.core.log.Log
    message: "This is an output: {{ outputs.generate_output.value }}"

  # Task 5: Use the input again to say goodbye.
  - id: goodbye_message
    type: io.kestra.plugin.core.log.Log
    message: "Goodbye, {{ inputs.name }}!"

# 6. PLUGIN DEFAULTS (The Global Rules)
# This says: "For EVERY task in this file that is a 'Log' task..."
# "...automatically set the log level to ERROR."
# This saves you from typing "level: ERROR" on all 3 log tasks above.
pluginDefaults:
  - type: io.kestra.plugin.core.log.Log
    values:
      level: ERROR

# 7. TRIGGERS (The Automation)
# This makes the flow run automatically without you clicking anything.
# Cron "0 10 * * *" means "Every day at 10:00 AM".
# We pass "Sarah" as the input specifically for these automatic morning runs.
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 * * *"
    inputs:
      name: Sarah
    disabled: true  # Disabled so it doesn't actually spam you while learning.